name: Deployment of Datafactory

on:
  push:
    branches:
      - main
    paths:
      - datafactory/**
      - .github/workflows/datafactoryDeploy.yml
      - scripts/datafactory/**

jobs:
# check_branch - branch protection rules for uat and prd | init - passes env variable

  init:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get_env.outputs.env }}
    steps:
      - id: get_env
        run: |
            echo "env=prod" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [init] 
    environment: "${{needs.init.outputs.environment}}"
    steps:
    - name: Checkout
      uses: actions/checkout@v3



    - name: Pre-run | Validate datafactory artifacts
      uses: Azure/data-factory-validate-action@v1.1.5
      with:
       path: datafactory/
    
    - name: Pre-run | Change permissions on datafactory folder
      run: |
         sudo chmod -R 777  datafactory

    - name: Export Azure Data Factory
      id: export
      uses: Azure/data-factory-export-action@v1.0.2
      with:
        path: datafactory/

    - name: Publish ARM template
      uses: actions/upload-artifact@v2
      with:
        name: adf-armtemplate
        path: ${{ steps.export.outputs.arm-template-directory }}
        if-no-files-found: error
    #- name: Pre-run | Disable triggers in workspace
     # shell: pwsh
     # run: |
     #   .\scripts\datafactory\modifyTriggers.ps1 -WorkspaceName datafactory-cicd-seb -action disable

  deploy:
    runs-on: ubuntu-latest
    needs: [init, build] 
    environment: "${{needs.init.outputs.environment}}"
    steps:
    - name: Pre-run | Checkout repository
      uses: actions/checkout@v2


    - name: Download ARM template
      id: download
      uses: actions/download-artifact@v3
      with:
        name: adf-armtemplate

    - name: Pre-run | Azure login
      uses: Azure/login@v1
      with:
        creds: '{
                    "clientId":"${{ secrets.AZURE_PRD_CLIENT_ID }}",
                    "clientSecret":"${{ secrets.AZURE_SP_SECRET }}",
                    "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                    "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                  }'
        enable-AzPSSession: true 

    - name: Datafactory workspace deployment
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        dataFactoryName: datafactory-cicd-seb
        resourceGroupName: datafactory-cicd
        armTemplateFile: "${{steps.download.outputs.download-path}}/ARMTemplateForFactory.json"

  deployProd:
    runs-on: ubuntu-latest
    needs: [init, build, deploy] 
    environment: "Production"
    steps:
    - name: Pre-run | Checkout repository
      uses: actions/checkout@v2
        
        
    - name: Download ARM template
      id: download
      uses: actions/download-artifact@v3
      with:
        name: adf-armtemplate
        
    - name: Pre-run | Azure login
      uses: Azure/login@v1
      with:
        creds: '{
                 "clientId":"${{ secrets.AZURE_PRD_CLIENT_ID }}",
                 "clientSecret":"${{ secrets.AZURE_SP_SECRET }}",
                 "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                  "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }'
        enable-AzPSSession: true 
        
    - name: Datafactory workspace deployment
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        dataFactoryName: datafactory-cicd-seb-prd
        resourceGroupName: datafactory-cicd
        armTemplateFile: "${{steps.download.outputs.download-path}}/ARMTemplateForFactory.json"
                