name: ValidateADF

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate_adf:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: Validate Data Factory resources
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
          id: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/datafactory-cicd/providers/Microsoft.DataFactory/factories/datafactory-cicd-seb